PythonProject1/masterfhoor/masterfhoor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('partner.urls', namespace='partners')),  # <-- добавить namespace
]

PythonProject1/masterfhoor/partner/urls.py
from django.urls import path
from . import views

app_name = 'partners'

urlpatterns = [
    path('', views.PartnerListView.as_view(), name='partner_list'),
    path('add/', views.PartnerCreateView.as_view(), name='partner_add'),
    path('<int:pk>/edit/', views.PartnerUpdateView.as_view(), name='partner_edit'),
    path('<int:pk>/sales-history/', views.SalesHistoryView.as_view(), name='sales_history'),
    path('<int:partner_id>/discount/', views.calculate_discount_api, name='calculate_discount'),
    path('calculate-material/', views.calculate_material_api, name='calculate_material'),
]

PythonProject1/masterfhoor/partner/models.py
from django.db import models
from django.core.validators import MinValueValidator, RegexValidator
from django.core.exceptions import ValidationError
import os


class ProductType(models.Model):
    name = models.CharField(max_length=255, verbose_name="Наименование")
    coefficient = models.FloatField(verbose_name="Коэффициент типа продукции")

    class Meta:
        verbose_name = "Тип продукции"
        verbose_name_plural = "Типы продукции"

    def __str__(self):
        return self.name


class MaterialType(models.Model):
    name = models.CharField(max_length=255, verbose_name="Наименование")
    defect_percentage = models.FloatField(verbose_name="Процент брака")

    class Meta:
        verbose_name = "Тип материала"
        verbose_name_plural = "Типы материалов"

    def __str__(self):
        return self.name


class Material(models.Model):
    material_type = models.ForeignKey(MaterialType, on_delete=models.CASCADE, verbose_name="Тип материала")
    name = models.CharField(max_length=255, verbose_name="Наименование")
    unit = models.CharField(max_length=50, verbose_name="Единица измерения")
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Стоимость")
    stock = models.IntegerField(verbose_name="Остатки")
    min_stock = models.IntegerField(verbose_name="Минимальный остаток")

    class Meta:
        verbose_name = "Материал"
        verbose_name_plural = "Материалы"

    def __str__(self):
        return self.name


class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE, verbose_name="Тип продукции")
    article = models.CharField(max_length=100, unique=True, verbose_name="Артикул")
    name = models.CharField(max_length=255, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание", blank=True)
    min_partner_cost = models.DecimalField(max_digits=10, decimal_places=2,
                                           verbose_name="Минимальная стоимость для партнера")

    class Meta:
        verbose_name = "Продукция"
        verbose_name_plural = "Продукция"

    def __str__(self):
        return f"{self.article} - {self.name}"


class PartnerType(models.Model):
    name = models.CharField(max_length=255, verbose_name="Наименование")

    class Meta:
        verbose_name = "Тип партнера"
        verbose_name_plural = "Типы партнеров"

    def __str__(self):
        return self.name


class Partner(models.Model):
    partner_type = models.ForeignKey(PartnerType, on_delete=models.CASCADE, verbose_name="Тип партнера")
    name = models.CharField(max_length=255, verbose_name="Наименование компании")
    rating = models.IntegerField(
        verbose_name="Рейтинг",
        validators=[MinValueValidator(0)]
    )
    address = models.TextField(verbose_name="Юридический адрес")
    director_name = models.CharField(max_length=255, verbose_name="ФИО директора")

    phone_regex = RegexValidator(
        regex=r'^\+7\d{10}$',
        message="Телефон должен быть в формате: '+79999999999'."
    )
    phone = models.CharField(
        validators=[phone_regex],
        max_length=12,
        verbose_name="Телефон"
    )

    email = models.EmailField(verbose_name="Email")
    inn = models.CharField(max_length=12, verbose_name="ИНН", blank=True)
    logo = models.ImageField(upload_to='partner_logos/', verbose_name="Логотип", blank=True)

    class Meta:
        verbose_name = "Партнер"
        verbose_name_plural = "Партнеры"
        ordering = ['-rating', 'name']

    def __str__(self):
        return self.name

    def calculate_discount(self):
        total_sales = SalesHistory.objects.filter(partner=self).aggregate(
            total=models.Sum('quantity')
        )['total'] or 0

        if total_sales > 300000:
            return 15
        elif total_sales > 50000:
            return 10
        elif total_sales > 10000:
            return 5
        else:
            return 0


class SalesHistory(models.Model):
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE, verbose_name="Партнер")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукция")
    quantity = models.IntegerField(verbose_name="Количество", validators=[MinValueValidator(1)])
    sale_date = models.DateField(verbose_name="Дата продажи")

    class Meta:
        verbose_name = "История реализации"
        verbose_name_plural = "История реализации"
        ordering = ['-sale_date']

    def __str__(self):
        return f"{self.partner.name} - {self.product.name} - {self.sale_date}"


class Recipe(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукция")
    material = models.ForeignKey(Material, on_delete=models.CASCADE, verbose_name="Материал")
    material_quantity = models.FloatField(verbose_name="Количество материала")

    class Meta:
        verbose_name = "Рецептура"
        verbose_name_plural = "Рецептура"
        unique_together = ['product', 'material']

    def __str__(self):
        return f"{self.product.name} - {self.material.name}"


def calculate_material_required(product_type_id, material_type_id, product_quantity, param1, param2):
    try:
        product_type = ProductType.objects.get(id=product_type_id)
        material_type = MaterialType.objects.get(id=material_type_id)

        if (product_quantity <= 0 or param1 <= 0 or param2 <= 0 or
                not isinstance(product_quantity, int)):
            return -1

        material_per_unit = param1 * param2 * product_type.coefficient

        total_material = material_per_unit * product_quantity

        defect_factor = 1 + (material_type.defect_percentage / 100)
        total_material_with_defect = total_material * defect_factor

        return int(total_material_with_defect) + (1 if total_material_with_defect % 1 > 0 else 0)

    except (ProductType.DoesNotExist, MaterialType.DoesNotExist):
        return -1

PythonProject1/masterfhoor/partner/forms.py
from django import forms
from .models import Partner, SalesHistory, PartnerType


class PartnerForm(forms.ModelForm):
    class Meta:
        model = Partner
        fields = [
            'name', 'partner_type', 'rating', 'address',
            'director_name', 'phone', 'email', 'inn', 'logo'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'partner_type': forms.Select(attrs={'class': 'form-control'}),
            'rating': forms.NumberInput(attrs={'class': 'form-control', 'min': '0'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'director_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+79999999999'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'inn': forms.TextInput(attrs={'class': 'form-control'}),
            'logo': forms.FileInput(attrs={'class': 'form-control'}),
        }

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if rating < 0:
            raise forms.ValidationError("Рейтинг должен быть неотрицательным числом")
        return rating


class SalesHistoryFilterForm(forms.Form):
    date_from = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        label='С даты'
    )
    date_to = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        label='По дату'
    )

PythonProject1/masterfhoor/partner/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.db.models import Sum
from .models import Partner, SalesHistory, PartnerType, ProductType, MaterialType
from .forms import PartnerForm, SalesHistoryFilterForm


def calculate_material_required(product_type_id, material_type_id, product_quantity, param1, param2):
    try:
        product_type = ProductType.objects.get(id=product_type_id)
        material_type = MaterialType.objects.get(id=material_type_id)
        if (product_quantity <= 0 or param1 <= 0 or param2 <= 0 or
                not isinstance(product_quantity, int)):
            return -1
        material_per_unit = param1 * param2 * product_type.coefficient
        total_material = material_per_unit * product_quantity
        defect_factor = 1 + (material_type.defect_percentage / 100)
        total_material_with_defect = total_material * defect_factor
        return int(total_material_with_defect) + (1 if total_material_with_defect % 1 > 0 else 0)

    except (ProductType.DoesNotExist, MaterialType.DoesNotExist, ValueError):
        return -1


class PartnerListView(ListView):
    model = Partner
    template_name = 'partners/partner_list.html'
    context_object_name = 'partners'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        partner_type = self.request.GET.get('partner_type')
        search = self.request.GET.get('search')

        if partner_type:
            queryset = queryset.filter(partner_type_id=partner_type)
        if search:
            queryset = queryset.filter(name__icontains=search)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['partner_types'] = PartnerType.objects.all()
        return context


class PartnerCreateView(CreateView):
    model = Partner
    form_class = PartnerForm
    template_name = 'partners/partner_form.html'
    success_url = reverse_lazy('partners:partner_list')

    def form_valid(self, form):
        messages.success(self.request, 'Партнер успешно добавлен')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Пожалуйста, исправьте ошибки в форме')
        return super().form_invalid(form)


class PartnerUpdateView(UpdateView):
    model = Partner
    form_class = PartnerForm
    template_name = 'partners/partner_form.html'
    success_url = reverse_lazy('partners:partner_list')

    def form_valid(self, form):
        messages.success(self.request, 'Данные партнера успешно обновлены')
        return super().form_valid(form)


class SalesHistoryView(DetailView):
    model = Partner
    template_name = 'partners/sales_history.html'
    context_object_name = 'partner'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        partner = self.get_object()

        sales_history = SalesHistory.objects.filter(partner=partner)

        form = SalesHistoryFilterForm(self.request.GET)
        if form.is_valid():
            date_from = form.cleaned_data.get('date_from')
            date_to = form.cleaned_data.get('date_to')

            if date_from:
                sales_history = sales_history.filter(sale_date__gte=date_from)
            if date_to:
                sales_history = sales_history.filter(sale_date__lte=date_to)

        context['sales_history'] = sales_history
        context['filter_form'] = form
        context['total_sales'] = sales_history.aggregate(total=Sum('quantity'))['total'] or 0
        context['current_discount'] = partner.calculate_discount()

        return context


def calculate_discount_api(request, partner_id):
    partner = get_object_or_404(Partner, id=partner_id)
    discount = partner.calculate_discount()
    return JsonResponse({'discount': discount})


def calculate_material_api(request):
    try:
        product_type_id = int(request.GET.get('product_type_id', 0))
        material_type_id = int(request.GET.get('material_type_id', 0))
        product_quantity = int(request.GET.get('product_quantity', 0))
        param1 = float(request.GET.get('param1', 0))
        param2 = float(request.GET.get('param2', 0))

        result = calculate_material_required(
            product_type_id, material_type_id, product_quantity, param1, param2
        )

        return JsonResponse({'material_required': result})

    except (ValueError, TypeError):
        return JsonResponse({'error': 'Неверные параметры'}, status=400)

PythonProject1/masterfhoor/partner/templates/partners/partner_form.html
{% extends 'base.html' %}

{% block title %}{% if form.instance.pk %}Редактирование партнера{% else %}Добавление партнера{% endif %}{% endblock %}

{% block content %}
<h2>{% if form.instance.pk %}Редактирование партнера{% else %}Добавление партнера{% endif %}</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
        {{ field }}
        {% if field.errors %}
        <div style="color: red; font-size: 12px; margin-top: 0.25rem;">
            {{ field.errors }}
        </div>
        {% endif %}
        {% if field.help_text %}
        <div style="color: #666; font-size: 12px; margin-top: 0.25rem;">
            {{ field.help_text }}
        </div>
        {% endif %}
    </div>
    {% endfor %}
    
    <div style="display: flex; gap: 1rem; margin-top: 2rem;">
        <button type="submit" class="btn">
            {% if form.instance.pk %}Сохранить изменения{% else %}Добавить партнера{% endif %}
        </button>
        <a href="{% url 'partners:partner_list' %}" class="btn" style="background-color: #6c757d;">Отмена</a>
    </div>
</form>
{% endblock %}

PythonProject1/masterfhoor/partner/templates/partners/partner_list.html
{% extends 'base.html' %}

{% block title %}Список партнеров{% endblock %}

{% block content %}
<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
    <h2>Список партнеров</h2>
    <a href="{% url 'partners:partner_add' %}" class="btn">Добавить партнера</a>
</div>
<div style="background-color: #F4E8D3; padding: 1rem; border-radius: 4px; margin-bottom: 1rem;">
    <form method="get" style="display: flex; gap: 1rem; align-items: end;">
        <div class="form-group" style="flex: 1;">
            <label for="search">Поиск по наименованию:</label>
            <input type="text" id="search" name="search" class="form-control" 
                   value="{{ request.GET.search }}" placeholder="Введите название компании...">
        </div>
        <div class="form-group">
            <label for="partner_type">Тип партнера:</label>
            <select id="partner_type" name="partner_type" class="form-control">
                <option value="">Все типы</option>
                {% for type in partner_types %}
                <option value="{{ type.id }}" 
                       {% if request.GET.partner_type == type.id|stringformat:"i" %}selected{% endif %}>
                    {{ type.name }}
                </option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn">Применить</button>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Тип партнера</th>
            <th>Рейтинг</th>
            <th>Телефон</th>
            <th>Email</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for partner in partners %}
        <tr>
            <td>{{ partner.name }}</td>
            <td>{{ partner.partner_type.name }}</td>
            <td>{{ partner.rating }}</td>
            <td>{{ partner.phone }}</td>
            <td>{{ partner.email }}</td>
            <td>
                <a href="{% url 'partners:partner_edit' partner.pk %}" class="btn" style="margin-right: 0.5rem;">
                    Редактировать
                </a>
                <a href="{% url 'partners:sales_history' partner.pk %}" class="btn">
                    История продаж
                </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="6" style="text-align: center;">Партнеры не найдены</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if is_paginated %}
<div style="display: flex; justify-content: center; margin-top: 2rem;">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" 
       class="btn" style="margin-right: 0.5rem;">Назад</a>
    {% endif %}
    
    <span style="padding: 0.5rem 1rem;">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" 
       class="btn" style="margin-left: 0.5rem;">Вперед</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}

PythonProject1/masterfhoor/partner/templates/partners/sales_history.html
{% extends 'base.html' %}

{% block title %}История продаж - {{ partner.name }}{% endblock %}

{% block content %}
<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
    <h2>История продаж: {{ partner.name }}</h2>
    <a href="{% url 'partners:partner_list' %}" class="btn">Назад к списку</a>
</div>
<div style="background-color: #F4E8D3; padding: 1rem; border-radius: 4px; margin-bottom: 2rem;">
    <h3>Информация о партнере</h3>
    <p><strong>Текущая скидка:</strong> {{ current_discount }}%</p>
    <p><strong>Общее количество продаж:</strong> {{ total_sales }} шт.</p>
</div>
<div style="margin-bottom: 2rem;">
    <form method="get" style="display: flex; gap: 1rem; align-items: end;">
        {{ filter_form.as_p }}
        <button type="submit" class="btn">Применить фильтр</button>
    </form>
</div>
{% if sales_history %}
<table class="table">
    <thead>
        <tr>
            <th>Наименование продукции</th>
            <th>Количество</th>
            <th>Дата продажи</th>
        </tr>
    </thead>
    <tbody>
        {% for sale in sales_history %}
        <tr>
            <td>{{ sale.product.name }}</td>
            <td>{{ sale.quantity }} шт.</td>
            <td>{{ sale.sale_date|date:"d.m.Y" }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div style="text-align: center; padding: 2rem; background-color: #f8f9fa; border-radius: 4px;">
    <p>История продаж не найдена</p>
</div>
{% endif %}
{% endblock %}